# Generated by Django 4.2.1 on 2023-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MissingChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="missing_children/")),
                ("image_encoding", models.BinaryField()),
                ("date_missing", models.DateField()),
                ("place_of_birth", models.CharField(max_length=100)),
                ("last_seen", models.CharField(max_length=100)),
                ("guardian_name", models.CharField(max_length=100)),
                ("guardian_contact", models.CharField(max_length=50)),
            ],
        ),
    ]
