# Generated by Django 4.2.1 on 2023-05-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingchild",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
