# Generated by Django 4.2.1 on 2023-05-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("picApp", "0002_alter_missingchild_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingchild",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="O",
                max_length=1,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="missingchild",
            unique_together={("name", "age", "gender", "date_missing")},
        ),
    ]
