# Generated by Django 5.0.1 on 2024-04-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0004_foundperson_alter_missingchild_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missingchild',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
    ]
