# Generated by Django 5.0.1 on 2024-04-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0005_foundperson_isverified_missingchild_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='image_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
