# Generated by Django 5.0.1 on 2024-04-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0006_foundperson_image_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundperson',
            name='image_encoding',
            field=models.BinaryField(),
        ),
    ]
