# Generated by Django 5.0.1 on 2024-04-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0007_alter_foundperson_image_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='isfound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missingchild',
            name='isfound',
            field=models.BooleanField(default=False),
        ),
    ]
