# Generated by Django 5.0.1 on 2024-04-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picApp', '0008_foundperson_isfound_missingchild_isfound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundperson',
            name='isfound',
        ),
        migrations.RemoveField(
            model_name='missingchild',
            name='isfound',
        ),
    ]
